schema_version: 2
source_family: pocket-monsters-green-japan

input:
  platform: Game Boy
  mapper: MBC1+RAM+BATTERY
  revisions:
    - id: jp-green-rev0
      header_revision: 0
      sha256: 6576b4e0979e93d4a6fa02db893c294b7aeab3b841b1acc8658bc10b3554f33c
    - id: jp-green-reva
      header_revision: 1
      sha256: 3f0dc460ca8d06be1c9ac96307c939c0ea7baa366b40c2f1f4ad63242b6c4816

target:
  platform: Game Boy / Super Game Boy
  strategy: expand-original-rom
  mapper: MBC5+RAM+BATTERY
  preserve_source_banks: true
  external_engine: null
